package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/ghodss/yaml"
	"github.com/recolude/swagger-unity-codegen/unitygen"
	"github.com/recolude/swagger-unity-codegen/unitygen/convention"
	"github.com/recolude/swagger-unity-codegen/unitygen/model"
	"github.com/recolude/swagger-unity-codegen/unitygen/security"
	"github.com/spf13/afero"
	"github.com/urfave/cli/v2"
)

func fileCommentHeader(out io.Writer) {
	fmt.Fprintln(out, "// This code was generated by: ")
	fmt.Fprintln(out, "// https://github.com/recolude/swagger-unity-codegen")
	fmt.Fprintln(out, "// Issues and PRs welcome :)")
	fmt.Fprintln(out, "")
}

func fileImports(out io.Writer) {
	fmt.Fprintln(out, "using UnityEngine;")
	fmt.Fprintln(out, "using UnityEngine.Networking;")
	fmt.Fprintln(out, "using System.Collections;")
	fmt.Fprintln(out, "using System.Text;")
	fmt.Fprintln(out, "using Newtonsoft.Json;")
	fmt.Fprintln(out, "using Newtonsoft.Json.Converters;")
	fmt.Fprintln(out, "using JsonSubTypes;")
	fmt.Fprintln(out, "")
}

func writeDefinitions(out io.Writer, defs []model.Definition) {
	for _, def := range defs {
		fmt.Fprintf(out, "%s\n\n", def.ToCSharp())
	}
}

func namespaceToUnityAssetMenu(namespace string) string {
	if namespace == "" {
		return "API"
	}
	return strings.Replace(namespace, ".", "/", -1)
}

func writeService(out io.Writer, service unitygen.Service, authDefinitions []security.Auth, namespace string, configName string) {

	serviceNamespace := namespace

	if serviceNamespace != "" {
		serviceNamespace += "."
	}

	serviceNamespace += service.ClassName()

	openNamespace(out, serviceNamespace)
	fmt.Fprintf(out, "%s\n\n", service.ToCSharp(authDefinitions, configName, namespaceToUnityAssetMenu(namespace)))
	closeNamespace(out, serviceNamespace)
}

func writeServiceProvider(out io.Writer, service unitygen.Service, namespace string) {

	serviceNamespace := namespace

	if serviceNamespace != "" {
		serviceNamespace += "."
	}

	serviceNamespace += service.ClassName()

	openNamespace(out, serviceNamespace)
	fmt.Fprintf(out, "%s\n", service.ServiceProvider(namespaceToUnityAssetMenu(namespace)))
	closeNamespace(out, serviceNamespace)
}

func openNamespace(out io.Writer, namespace string) {
	if namespace == "" {
		return
	}
	fmt.Fprintf(out, "namespace %s {\n\n", convention.TitleCase(namespace))
}

func closeNamespace(out io.Writer, namespace string) {
	if namespace == "" {
		return
	}
	fmt.Fprint(out, "}")
}

func toDir(fs afero.Fs, c *cli.Context, location string, spec unitygen.Spec) error {
	namespace := c.String("namespace")

	err := fs.MkdirAll(location, os.ModePerm)
	if err != nil {
		return fmt.Errorf("error creating folder: %w", err)
	}

	definitionsFile, err := fs.Create(path.Join(location, "Definitions.cs"))
	if err != nil {
		return fmt.Errorf("error creating definitions file: %w", err)
	}
	defer definitionsFile.Close()
	fileCommentHeader(definitionsFile)
	fileImports(definitionsFile)
	openNamespace(definitionsFile, namespace)
	writeDefinitions(definitionsFile, spec.Definitions)
	closeNamespace(definitionsFile, namespace)

	configNameTitleCase := convention.TitleCase(c.String("config-name"))

	for _, service := range spec.Services {
		servicesFile, err := fs.Create(path.Join(location, fmt.Sprintf("%s.cs", service.ClassName())))
		if err != nil {
			return fmt.Errorf("error creating services file: %w", err)
		}
		defer servicesFile.Close()

		fileCommentHeader(servicesFile)
		fileImports(servicesFile)
		writeService(servicesFile, service, spec.AuthDefinitions, namespace, configNameTitleCase)

		servicesProviderFile, err := fs.Create(path.Join(location, fmt.Sprintf("%sProvider.cs", service.ClassName())))
		if err != nil {
			return fmt.Errorf("error creating services provider file: %w", err)
		}
		defer servicesProviderFile.Close()

		fileCommentHeader(servicesProviderFile)
		fileImports(servicesProviderFile)
		writeServiceProvider(servicesProviderFile, service, namespace)
	}

	configFile, err := fs.Create(path.Join(location, fmt.Sprintf("%s.cs", configNameTitleCase)))
	if err != nil {
		return fmt.Errorf("error creating config file: %w", err)
	}
	defer configFile.Close()
	fileCommentHeader(configFile)
	fileImports(configFile)
	openNamespace(configFile, namespace)
	fmt.Fprintf(configFile, "%s\n\n", spec.ServiceConfig(c.String("config-name"), namespaceToUnityAssetMenu(namespace)+"/"+c.String("config-name"), c.Bool("scriptable-object-config")))
	closeNamespace(configFile, namespace)

	return nil
}

func buildApp(fs afero.Fs, out io.Writer, errOut io.Writer) *cli.App {
	return &cli.App{
		Name:        "swag3d",
		Description: "Generate C# code specifically for Unity3D from a swagger file",
		Version:     "0.1.0",
		Usage:       "swagger and Unity3D meet",
		Writer:      out,
		ErrWriter:   errOut,
		Authors: []*cli.Author{
			{
				Name: "Elijah C Davis",
			},
		},
		Flags: []cli.Flag{},
		Commands: []*cli.Command{
			{
				Name:    "generate",
				Aliases: []string{"g"},
				Usage:   "Generate c# code from a swagger file",
				Flags: []cli.Flag{
					&cli.StringFlag{
						Name:  "namespace",
						Usage: "The namespace the code will be wrapped in",
					},
					&cli.StringFlag{
						Name:        "config-name",
						Usage:       "The name of the config class that will contain all server variables",
						Value:       "ServiceConfig",
						DefaultText: "ServiceConfig",
					},
					&cli.StringFlag{
						Name:    "file",
						Aliases: []string{"f"},
						Usage:   "where to load swagger from",
						Value:   "swagger.json",
					},
					&cli.BoolFlag{
						Name:  "include-unused",
						Usage: "Whether or not to include definitions that where never used in the different services",
						Value: false,
					},
					&cli.BoolFlag{
						Name:  "scriptable-object-config",
						Usage: "Whether or not to generate a scriptable object that contains all server values different services will use.",
						Value: true,
					},
					&cli.StringSliceFlag{
						Name:  "tags",
						Usage: "Specify tags that a route must have to be included in the export. Specifying no tags means include all routes",
					},

					&cli.StringFlag{
						Name:        "out",
						Usage:       "The directory where you want the contents to be written to disc",
						DefaultText: "",
					},
				},
				Action: func(c *cli.Context) error {
					fileToLoad := c.String("file")
					extension := strings.ToLower(filepath.Ext(fileToLoad))

					var jsonStream io.Reader

					switch extension {
					case ".json":
						file, err := fs.Open(fileToLoad)
						if err != nil {
							return fmt.Errorf("error opening swagger file: %w", err)
						}
						defer file.Close()
						jsonStream = file

					case ".yaml":
						fallthrough
					case ".yml":
						y, err := os.ReadFile(fileToLoad)
						if err != nil {
							return fmt.Errorf("error reading YAML: %w", err)
						}

						j2, err := yaml.YAMLToJSON(y)
						if err != nil {
							return fmt.Errorf("error translating YAML: %w", err)
						}
						jsonStream = bytes.NewBuffer(j2)

					default:
						return fmt.Errorf("unrecognized swagger file format '%s', please provide either json or yml", extension)
					}

					spec, err := unitygen.NewParser().ParseJSON(jsonStream)
					if err != nil {
						return fmt.Errorf("error reading from swagger file: %w", err)
					}
					spec = filterSpecForTags(spec, c.StringSlice("tags"))
					if !c.Bool("include-unused") {
						spec = filterSpecForUnusedDefinitions(spec)
					}

					return toDir(fs, c, c.String("out"), spec)
				},
			},
		},
	}
}

func main() {
	app := buildApp(afero.NewOsFs(), os.Stdout, os.Stderr)
	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
